### ISSUE TITLE
Power sector constraints

### ISSUE THREAD

**Issue by daly-h** [MaREI-EPMG/tim-gas-study-2022#1]
- Increase 2022 onshore wind capacity to 4.3GW in 2022 ([source](https://windenergyireland.com/about-wind/facts-stats))
- Limit NCap for onshore wind to 0.5GW per year ([source](https://en.wikipedia.org/wiki/Wind_power_in_Ireland#/media/File:Sustainable_Energy_Authority_of_Ireland_SEAI_2019_Ireland_wind_power_generating_capacity_2000-2018.png)).. this is necessary to achieve 8GW in 2030 as CAP21
- START offshore wind at 2025 and NCAP at 1GW/year ..? 
- No new hydro
- START CCS 2035

Share of indigenous production 2020-2022 as attached. 
[Electricity_Monthly_Timeseries.csv](https://github.com/MaREI-EPMG/tim-gas-study-2022/files/9564999/Electricity_Monthly_Timeseries.csv)

**Comment by olejandro** [comment]
- [x] Increased 2022 onshore wind capacity to 4.7GW based on the [capacity statement](http://www.eirgridgroup.com/site-files/library/EirGrid/208281-All-Island-Generation-Capacity-Statement-LR13A.pdf)
- [x] LImited NCAP for Wind to 0.5GW
- [x] Offshore available from 2026 at 1GW/yr
- [x] No new hydro
- [x] CCS from 2035

**Comment by daly-h** [comment]
Could we change the offshore deployment to 2gw/year from 2027 please
