### ISSUE TITLE
DH and HP in SER

### ISSUE THREAD

**Issue by daly-h** [MaREI-EPMG/tim-gas-study-2022#14]
Great to see the work in DH come through. Could you consider adding some growth constraints to DH so it's not all delivered in 2023? :-) 

Also can you check the level of ambient heat in this sector already in 2020.

![image](https://user-images.githubusercontent.com/69575632/193360996-7ff97d6d-8456-43a0-bed6-a8fcae263719.png)

**Comment by olejandro** [comment]
Added a max growth constraint for DH and changed the one for ambient heat. Constrained ambient heat to EB values for 2019-2021. Should look different in the new results.
