### ISSUE TITLE
New scenario: BECCS (+Sectoral CBs)

### ISSUE THREAD

**Issue by daly-h** [MaREI-EPMG/tim-gas-study-2022#16]
Diagnostic to see how far we get to net-zero

**Comment by olejandro** [comment]
Could you elaborate a bit further on what you have in mind?

**Comment by daly-h** [comment]
Ha, sorry I forgot to add crucial detail, I meant *no BECCS*

**Comment by olejandro** [comment]
Ok. :-)
Regarding DC demand projections, Do you want to apply them to all scenarios (i.e. x3) or only to some?
