### ISSUE TITLE
Remove WholeCBs scenario

### ISSUE THREAD

**Issue by daly-h** [MaREI-EPMG/tim-gas-study-2022#17]
No longer relevant

**Comment by daly-h** [comment]
Also I don't think we need both Baseline and No Mitigation - what is the difference?

**Comment by olejandro** [comment]
We started working on scenario descriptions [here](https://github.com/MaREI-EPMG/tim-carbon-budgets-2022/blob/main/study/scenarios.md). I can remove it also in the next iteration.

**Comment by daly-h** [comment]
Thanks for the reminder. For the gas study we will have a limited number of scenarios. Will continue to work on the Sectoral CBs study when this is in.
