### ISSUE TITLE
Residential retrofits

### ISSUE THREAD

**Issue by daly-h** [MaREI-EPMG/tim-gas-study-2022#3]
Too many retrofits in 2023 (250k) - limit to max:
20k/year in 2023, 
30k/year in 2024
40k/year in 2025
50k/year in 2026
60k/year each year following

**Comment by olejandro** [comment]
Seems like it is not a problem in the latest results (5b464f10e3855181f8fd4c5ea685ced29a6de195)
Do you think it is worth specifying those rennovation rates anyway?

**Comment by olejandro** [comment]
@daly-h what do you think?

**Comment by daly-h** [comment]
There appears to be a wider issue with mitigation in the residential sector that needs to be resolved - there is a significant amount of unmitigated GHGs especially in CB2 but ongoing coal and peat use, and now limited retrofits in CB2. So I would not specify renovation rates until this is resolved.

**Comment by olejandro** [comment]
Ok, agreed!
