### ISSUE TITLE
Transport freight transport capacity factors

### ISSUE THREAD

**Issue by daly-h** [MaREI-EPMG/tim-gas-study-2022#6]
Vahid can you investigate freight tonne-kms/vehicle in new freight vehicles please? I expect they are higher for new vehicles as we are seeing a dip in the total freight stock in the 2020s. I would expect the stock to track overall demand. Thank you. 

https://epmg.netlify.app/tim-gas-study-2022/results/transport/vehicle-sales-and-stock

**Comment by olejandro** [comment]
Seems to be gone in b473030f3dd4ca5e077489f182c69216ff389222
